# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#   
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Major.create(:name => 'Daley', :city => cities.first)
Hatsize.create(:name=>"Small")
Hatsize.create(:name=>"Tiny")
Hatsize.create(:name=>"Fits All")
Hatsize.create(:name=>"Normal")
Hatsize.create(:name=>"Fathead")
User.create(:first_name=>"Larry", :last_name=>"Evans",:hatsize_id=>1)
User.create(:first_name=>"Armando", :last_name=>"Davis",:hatsize_id=>2)
User.create(:first_name=>"Wally", :last_name=>"Ginelli",:hatsize_id=>3)
User.create(:first_name=>"JoJo", :last_name=>"Abu",:hatsize_id=>4)
User.create(:first_name=>"Tim", :last_name=>"Garth",:hatsize_id=>2)
User.create(:first_name=>"Harvey", :last_name=>"Garlic",:hatsize_id=>4)
User.create(:first_name=>"Frederick", :last_name=>"Zane",:hatsize_id=>2)
User.create(:first_name=>"William", :last_name=>"Sims",:hatsize_id=>4)
User.create(:first_name=>"Marty", :last_name=>"Powell",:hatsize_id=>3)
User.create(:first_name=>"George", :last_name=>"Wall",:hatsize_id=>4)
Comment.create(:user_id=>1, :text=>"how do you do?")
Comment.create(:user_id=>2, :text=>"how do you do?")
Comment.create(:user_id=>3, :text=>"how do you do?")
Comment.create(:user_id=>4, :text=>"how do you do?")
Comment.create(:user_id=>5, :text=>"how do you do?")
Comment.create(:user_id=>6, :text=>"how do you do?")
Comment.create(:user_id=>7, :text=>"how do you do?")
Comment.create(:user_id=>8, :text=>"how do you do?")
Comment.create(:user_id=>9, :text=>"how do you do?")
Comment.create(:user_id=>1, :text=>"how do you do?")
Comment.create(:user_id=>1, :text=>"how do you do?")
Comment.create(:user_id=>2, :text=>"how do you do?")
Comment.create(:user_id=>2, :text=>"how do you do?")
Comment.create(:user_id=>3, :text=>"how do you do?")
Comment.create(:user_id=>3, :text=>"how do you do?")
Address.create(:user_id=>1,:street=>"5 North Main", :city=>"Arka", :state=>"NM", :zip=>"59593")
Address.create(:street=>"5 North Main", :city=>"Arka", :state=>"NM", :zip=>"59593")
Address.create(:user_id=>2,:street=>"5 North Main", :city=>"Arka", :state=>"NM", :zip=>"59593")
Address.create(:user_id=>3,:street=>"5 North Main", :city=>"Arka", :state=>"NM", :zip=>"59593")
Address.create(:user_id=>4,:street=>"5 North Main", :city=>"Arka", :state=>"NM", :zip=>"59593")
Address.create(:user_id=>5,:street=>"5 North Main", :city=>"Arka", :state=>"NM", :zip=>"59593")
Address.create(:user_id=>6,:street=>"5 North Main", :city=>"Arka", :state=>"NM", :zip=>"59593")
Address.create(:user_id=>7,:street=>"5 North Main", :city=>"Arka", :state=>"NM", :zip=>"59593")
Address.create(:user_id=>8,:street=>"5 North Main", :city=>"Arka", :state=>"NM", :zip=>"59593")



